### ISSUE TITLE
Define the required Helm Charts to deploy the Wallet in a Kubernetes Cluster

### ISSUE THREAD

**Issue by oriolcanadesin2** [in2workspace/in2-dome-iac#19]

**Comment by said-ibrihen-orange** [comment]
Good new, Stefan from FIWARE informed us that we can deploy the charts by submitting a PR to the DOME GitOps repository : https://github.com/DOME-Marketplace/dome-gitops

**Comment by said-ibrihen-orange** [comment]
For testing purposes we can directly create a testing environment using the insctructions in the DOME GitOps README. We can validate the Helm configuration and then submit a PR to the DOME GitOps once everything is stabilized.

**Comment by said-ibrihen-orange** [comment]
For the testing environment here are the steps I suggest to follow :

1. Create IONOS testing environment based on the DOME GitOps repository.
1. Add a first Helm chart (wallet-wca for example) to test the deployment on IONOS
1. When the first Helm chart is successfuly deployed we can start adding the Helm chart for the other components

**Comment by said-ibrihen-orange** [comment]
Progress made so far : 

- Kubernetes cluster creation ✔ 
- ArgoCD installation ✔ 
- Sealed secrets creation ✔

Next steps : 

- Deploy mysql database  ✔
